In [1]:
import pandas as pd
import gspread as gs

In [2]:
gc = gs.service_account(filename='/Users/mattraghu/Documents/SheetsCred.json')

In [3]:
sh = gc.open_by_url('https://docs.google.com/spreadsheets/d/1tfZk4L2KwrIManlv2HuIS2hBDP5d1CmnyV9fBcpGwB4/edit?usp=sharing')

In [4]:
ws = sh.worksheet('Sheet1')

In [5]:
df = pd.DataFrame(ws.get_all_records())
df.head()

  Molecular Weight Range (g/mol)    xi    wi  Average Molecular Weight
0                  18000 - 33000  0.04  0.01                     25500
1                  33000 - 48000  0.07  0.04                     40500
2                  48000 - 63000  0.16  0.11                     55500
3                  63000 - 78000  0.26  0.24                     70500
4                  78000 - 93000  0.24  0.27                     85500

In [8]:
#Insert a column denoting the number-average moecular weight (Average Molecular Weight * xi)
df['Number Average Molecular Weight'] = df['Average Molecular Weight'] * df['xi']

#Weight Average Molecular Weight 
df['Weight Average Molecular Weight'] = df['Average Molecular Weight'] * df['wi']

#Inset a row showing the sum of Average Molecular Weights
df.loc['Total'] = df.sum()

In [9]:
df

,Molecular Weight Range (g/mol),xi,wi,Average Molecular Weight,Number Average Molecular Weight,Weight Average Molecular Weight
0,18000 - 33000,0.04,0.01,25500,1020.0,255.0
1,33000 - 48000,0.07,0.04,40500,2835.0,1620.0
2,48000 - 63000,0.16,0.11,55500,8880.0,6105.0
3,63000 - 78000,0.26,0.24,70500,18330.0,16920.0
4,78000 - 93000,0.24,0.27,85500,20520.0,23085.0
5,93000 - 108000,0.12,0.16,100500,12060.0,16080.0
6,108000 - 123000,0.08,0.12,115500,9240.0,13860.0
7,123000- 138000,0.03,0.05,130500,3915.0,6525.0
Total,18000 - 3300033000 - 4800048000 - 6300063000 -...,1.00,1.00,624000,76800.0,84450.0